SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


SELECT * FROM ROADMAP.PRTCPT_DVC WHERE STUDY_PRTCPT_ID = 'PF1BLPH4'

SELECT * FROM ROADMAP.PRTCPT_DVC WHERE STUDY_PRTCPT_ID = 'CFI9I6K2'

SELECT * FROM ROADMAP.PRTCPT_DVC WHERE PRTCPT_DVC_ID = 20433