select *from ROADMAP.ext_srvy_rspns_stat where study_prtcpt_id = 'BH5BSI59';

SELECT 'Table' AS object_type, owner, table_name
FROM all_tables
UNION ALL
SELECT 'View', owner, view_name
FROM all_views;

SELECT * FROM all_tables WHERE owner = 'ROADMAP' order BY TABLE_NAME 

SELECT 'Table' AS Object_type, ROADMAP,  FROM all_tables

select *from roadmap.circadian_objects
/*SELECT DISTINCT PRTCPT_DVC_ID 
FROM ROADMAP.STUDY_METRIC_HEARTRATE */
select distinct(study_prtcpt_id) from roadmap.study_metric_aggregates where study_id = 101

SELECT * FROM roadmap.PRTCPT_DVC WHERE STUDY_ID IN (4, 6, 11, 19, 35, 57, 59, 69, 75, 86);

SELECT STUDY_ID FROM ROADMAP.STUDY

SELECT * FROM ROADMAP.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 1332

SELECT STUDY_METRIC_TYP_ID
SELECT * FROM ROADMAP.PATIENT_AGE_GROUPS 

select *from ROADMAP.ext_srvy_rspns_stat where ext_srvy_id = 1

SELECT * FROM ROADMAP.ext_srvy_rspns_stat where STUDY_PRTCPT_ID = '1R698VXW'
SELECT * FROM ROADMAP.EXT_SRVY

SELECT * FROM ROADMAP.EXT_SRVY WHERE ROWNUM = 0;

select * from ROADMAP.STUDY_METRIC_TYP

select count(study_id) from roadmap.ext_srvy

SELECT COUNT(DISTINCT) STUDY_PRTCPT_ID FROM ROADMAP.PRTCPT_DVC WHERE STUDY_ID = 201

SELECT * FROM ROADMAP.STUDY_PRTCPT WHERE STUDY_PRTCPT_ID = 'WSS35RBA'

select * FROM ROADMAP.STUDY_GROUPS
SELECT COUNT(STUDY_METRIC_ID) FROM ROADMAP.STUDY_METRIC_HEARTRATE

/* SELECT count(*FROM ROADMAP.PRTCPT_DVC WHERE PRTCPT_DVC_MODEL = 'iPhone')*/

SELECT COUNT (*) FROM ROADMAP.PRTCPT_DVC
SELECT *FROM ROADMAP.study_metric_steps where prtcpt_dvc_id = 27655


SELECT * FROM ROADMAP.PRTCPT_DVC WHERE STUDY_PRTCPT_ID IN ('9R635ZTE','B2XG1A56','846FA27M','NWYLNHF7','TUGRXQDH','HISGXBPE','VRM4NEGK','6UH2QBTR','GDEF52J4','NW5ZIG6X')

SELECT * FROM ROADMAP.PRTCPT_DVC WHERE PRTCPT_DVC_INTERNAL_ID = '50e6e96f-7645-43e0-9546-002532723843'
SELECT * FROM ROADMAP.PRTCPT_DVC WHERE PRTCPT_DVC_INTERNAL_ID = 'febe96d3-89d3-4bc6-97ee-7549423950d2'


select *from ROADMAP.PRTCPT_DVC WHERE STUDY_PRTCPT_ID = 'L9DED7AU'
SELECT "EXT_SRVY_RSPNS_STAT_ID", "EXT_SRVY_ID", "EXT_SRVY_TYP_ID", "STUDY_PRTCPT_ID", "STUDY_ID", "EXT_SRVY_RSPNS_STAT_RCPT_ID", "EXT_SRVY_RSPNS_STAT_RCPT_URL", "EXT_SRVY_RSPNS_STAT_RSPNS_ID", "EXT_SRVY_RSPNS_STAT_CD", "EXT_SRVY_RSPNS_STAT_START_DT", "EXT_SRVY_RSPNS_STAT_END_DT", "CRT_DT", "CRT_ID" FROM(
SELECT * FROM ROADMAP.ext_srvy_rspns_stat where STUDY_PRTCPT_ID = '1R698VXW'
)

SELECT STUDY_METRIC_PRTCPTN_IND FROM  ROADMAP.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 27

SELECT *  FROM  ROADMAP.STUDY_METRIC_STEPS where PRTCPT_DVC_ID = 26154
SELECT STUDY_METRIC_TYP_ID, STUDY_METRIC_MSR_VAL, STUDY_METRIC_MSR_START_DT FROM ROADMAP.STUDY_METRIC_STEPS WHERE PRTCPT_DVC_ID = 26154 

SELECT * FROM ROADMAP.STUDY_METRIC_STEPS WHERE TO_CHAR(TO_DATE(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS'), 'MI') = '00' AND PRTCPT_DVC_ID IN (26154, 26674, 27314, 26754, 26774, 26916, 27294, 27394, 27533, 26133, 26294, 26355, 26694, 26714, 26334, 26894, 26953, 27054, 27174, 27354, 26274, 26555, 27553, 26176, 26178, 27035, 27414);

SELECT * FROM ROADMAP.STUDY_METRIC_HEARTRATE WHERE TO_CHAR(TO_DATE(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS'), 'SS') != '00' AND PRTCPT_DVC_ID IN (26154, 26674, 27314, 26754, 26774, 26916, 27294, 27394, 27533, 26133, 26294, 26355, 26694, 26714, 26334, 26894, 26953, 27054, 27174, 27354, 26274, 26555, 27553, 26176, 26178, 27035, 27414);
SELECT * FROM ROADMAP.STUDY_METRIC_HEARTRATE WHERE TO_CHAR(TO_DATE(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS'), 'SS') != '00' 

SELECT * FROM ROADMAP.STUDY_METRIC_STEPS WHERE TO_CHAR(TO_DATE(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS'), 'SS') != '00' AND PRTCPT_DVC_ID IN (26154, 26674, 27414); /* Note - It took 412 seconds to execute. Answer was an exmpty matrix */

SELECT * FROM ROADMAP.STUDY_METRIC_STEPS WHERE TO_CHAR(TO_DATE(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS'), 'SS') != '00' AND PRTCPT_DVC_ID IN (26154); /* Note - It took 412 seconds to execute. Answer was an exmpty matrix */


select distinct(PRTCPT_DVC_ID) from roadmap.STUDY_METRIC_HEARTRATE
select distinct(PRTCPT_DVC_ID) from roadmap.PRTCPT_DVC

SELECT * FROM ROADMAP.ext_srvy_rspns_stat where STUDY_PRTCPT_ID = ('1R698VXW')

select distinct(study_prtcpt_id) from roadmap.study_metric_aggregates where study_id = 101

select distinct(study_prtcpt_id) from roadmap.study_metric_aggregates
SELECT distinct(study_prtcpt_id) FROM ROADMAP.STUDY_PRTCPT where study_id = 203 

SELECT * FROM ROADMAP.STUDY_PRTCPT where study_id = 101 

select *from roadmap.PRTCPT_DVC where STUDY_PRTCPT_ID  in ('CFI9I6K2','PF1BLPH4')

select STUDY_PRTCPT_ID ,PRTCPT_STATUS from ROADMAP.STUDY_PRTCPT where study_id = 101 

select STUDY_METRIC_MSR_VAL, STUDY_METRIC_MSR_START_DT from ROADMAP.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 1558

select * from ROADMAP.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 26154 and STUDY_METRIC_MSR_START_DT = '2023-03-07 00:00:00'

select * from ROADMAP.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 26154 and STUDY_METRIC_MSR_START_DT LIKE '2023-03-07%' ORDER BY STUDY_METRIC_MSR_START_DT ASC /* arrange them in an ascending order just to make sure*/


(SELECT count(*) AS TOTAL_CNT,STUDY_PRTCPT_ID AS RMAP_ID2 FROM ROADMAP.STUDY_METRIC_AGGREGATES WHERE STUDY_PRTCPT_ID in ('XEQBI7KQ','1ISU7PU3') GROUP BY STUDY_PRTCPT_ID)

select *from roadmap.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 1577

select *from roadmap.PRTCPT_DVC where STUDY_PRTCPT_ID = 'IHUCHGIT'
select *from roadmap.PRTCPT_DVC
select *from roadmap.STUDY_METRIC_STEPS where (PRTCPT_DVC_ID = 26154 AND STUDY_METRIC_MSR_START_DT = '2023-08-10 08:10:00')
select *from roadmap.STUDY_METRIC_STEPS where PRTCPT_DVC_ID = 26154

SELECT column_name 
FROM all_tab_columns 
WHERE table_name = 'PRTCPT_DVC' AND OWNER = 'ROADMAP';

SELECT column_name, data_type, data_length 
FROM all_tab_columns 
WHERE table_name = 'PRTCPT_DVC' AND OWNER = 'ROADMAP';

select * from roadmap.PRTCPT_DVC where PRTCPT_DVC_ID = 1332

/* Downloading steps and sleep data set for the participant ID '4UDRUW84' to implement the pipeline for heart rate, steps and sleep data set of wearables data set*/

select * from roadmap.PRTCPT_DVC where STUDY_PRTCPT_ID = '4UDRUW84'and PRTCPT_DVC_TYP_ID = 1
select * from roadmap.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID in (12115,17653,17655,17656,17658)
select * from roadmap.STUDY_METRIC_STEPS where PRTCPT_DVC_ID in (12115,17653,17655,17656,17658)
select * from roadmap.STUDY_METRIC_SLEEP where PRTCPT_DVC_ID in (12115,17653,17655,17656,17658)


