SELECT * FROM ROADMAP.study_metric_sleep
SELECT * FROM ROADMAP.SLEEP_SUMMARY WHERE ASLEEP_VALUE = 296 AND WAKE_MIN=24

SELECT * FROM ROADMAP.SLEEP_SUMMARY WHERE STUDY_PRTCPT_ID = 'NJD51JHD' AND ASLEEP_VALUE >200
SELECT ASLEEP_VALUE, ASLEEP_MIN, (ASLEEP_VALUE -  ASLEEP_MIN) AS DIFF_BTWN FROM ROADMAP.SLEEP_SUMMARY 

----------------------------------------------------------------------------------------------------
SELECT * FROM ROADMAP.SLEEP_SUMMARY WHERE TYPE = 'classic' AND ASLEEP_MIN > 180
----------------------------------------------------------------------------------------------------
SELECT *
FROM ROADMAP.SLEEP_SUMMARY
WHERE SLEEP_DATE IN (
    SELECT SLEEP_DATE
    FROM ROADMAP.SLEEP_SUMMARY
    WHERE TYPE = 'classic'
    AND ASLEEP_MIN > 180
);

-- confirmation that ASLEEP_VALUE and ASLEEP_MIN are the same 
SELECT ASLEEP_VALUE, ASLEEP_MIN, (ASLEEP_VALUE - ASLEEP_MIN) AS difference
FROM ROADMAP.SLEEP_SUMMARY
WHERE (ASLEEP_VALUE - ASLEEP_MIN) IS NOT NULL AND (ASLEEP_VALUE - ASLEEP_MIN) != 0;

--------------------------------------------------------------------
SELECT ASLEEP_VALUE, ASLEEP_MIN, (ASLEEP_VALUE - ASLEEP_MIN) AS difference
FROM ROADMAP.SLEEP_SUMMARY
WHERE (ASLEEP_VALUE - ASLEEP_MIN) IS NOT NULL ;
--------------------------------------------------------------------

-- Following statement confirms that if the RESTLESS_MIN value is present, then the sleep type is classic. But I will still have to check if for same day there is another type of sleep for that person as well. 
SELECT DISTINCT TYPE
FROM ROADMAP.SLEEP_SUMMARY
WHERE RESTLESS_MIN IS NOT NULL;

--------------------------------------------------
SELECT DISTINCT TYPE
FROM ROADMAP.SLEEP_SUMMARY
WHERE AWAKE_MIN IS NOT NULL;

SELECT * FROM ROADMAP.SLEEP_SUMMARY WHERE RESTLESS_MIN IS NOT NULL;
-------------------------------------------------------
-- How many rows each of the participants has
SELECT STUDY_PRTCPT_ID, COUNT(*) as num_rows
FROM ROADMAP.SLEEP_SUMMARY
GROUP BY STUDY_PRTCPT_ID; 
--------------
SELECT * FROM ROADMAP.SLEEP_SUMMARY WHERE STUDY_PRTCPT_ID = '1V8EJSPG'
---------------------------------------------------------------------------------
SELECT ASLEEP_VALUE, ASLEEP_MIN, INBED_VALUE, WAKE_MIN ,(INBED_VALUE - ASLEEP_VALUE - WAKE_MIN)AS DIFF 
FROM ROADMAP.SLEEP_SUMMARY WHERE (INBED_VALUE - ASLEEP_VALUE - WAKE_MIN) IS NOT NULL AND (INBED_VALUE - ASLEEP_VALUE - WAKE_MIN) !=0

--------------------------------------------------------------------------------------------------------------------------------------------------
SELECT ASLEEP_VALUE, ASLEEP_MIN, INBED_VALUE, WAKE_MIN , AWAKE_MIN, RESTLESS_MIN, (INBED_VALUE - ASLEEP_VALUE - WAKE_MIN - AWAKE_MIN)AS DIFF 
FROM ROADMAP.SLEEP_SUMMARY WHERE (INBED_VALUE - ASLEEP_VALUE - WAKE_MIN- AWAKE_MIN) !=0 AND (INBED_VALUE - ASLEEP_VALUE - WAKE_MIN- AWAKE_MIN) IS NOT NULL 

SELECT ASLEEP_VALUE, ASLEEP_MIN, INBED_VALUE, WAKE_MIN , AWAKE_MIN, RESTLESS_MIN, (INBED_VALUE - ASLEEP_VALUE - COALESCE(TO_NUMBER(WAKE_MIN),0) - COALESCE(TO_NUMBER(AWAKE_MIN),0) - COALESCE(TO_NUMBER(RESTLESS_MIN),0))AS DIFF 
FROM ROADMAP.SLEEP_SUMMARY WHERE  ((INBED_VALUE) - (ASLEEP_VALUE) - COALESCE(TO_NUMBER(WAKE_MIN), 0) - COALESCE(TO_NUMBER(AWAKE_MIN), 0) - COALESCE(TO_NUMBER(RESTLESS_MIN),0)) IS NOT NULL
  AND ((INBED_VALUE) - (ASLEEP_VALUE) - COALESCE(TO_NUMBER(WAKE_MIN), 0) - COALESCE(TO_NUMBER(AWAKE_MIN), 0)- COALESCE(TO_NUMBER(RESTLESS_MIN),0)) != 0;


SELECT * FROM ROADMAP.SLEEP_SUMMARY
WHERE LIGHT_MIN != 0 AND LIGHT_MIN IS NOT NULL;