
SELECT * from roadmap.PRTCPT_DVC WHERE STUDY_PRTCPT_ID IN ('RYFXBDFQ', 'XGJ8AFS8', 'TQLY4RDR', 'MLYS5U85', 'UQUEK1XU', '8MRVHIRR', 'VL61MMTY', 'YRTQ7TKL', 'IS69SBYZ', 'T4CSRKVM', '15LGWNGJ', '1X8MBFBA', 'N5F15GYZ', 'Y8PEMP7K', 'D1C3M5J2', 'RQ5P4ZR8', 'W7LX2I74', '3IJBZPI8', '5NQHT686', 'M5ENQMEA', 'SBTLFFUR', 'F1MALNM8', 'JEW6KQY3', 'VZK8IVKE', 'XKZF8SDS', 'JU3R5P4M', 'KL8ZU5XC', 'CCD84K8N') and prtcpt_dvc_typ_id=1

SELECT * from roadmap.STUDY_METRIC_HEARTRATE WHERE PRTCPT_DVC_ID IN (26154, 26674, 27314, 26754, 26774, 26916, 27294, 27394, 27533, 26133, 26294, 26355, 26694, 26714, 26334, 26894, 26953, 27054, 27174, 27354, 26274, 26555, 27553, 26176, 26178, 27035, 27414)

SELECT * from roadmap.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 1558


SELECT  STUDY_METRIC_MSR_START_DT, STUDY_METRIC_MSR_END_DT, (STUDY_METRIC_MSR_END_DT - STUDY_METRIC_MSR_START_DT) AS time_difference_in_minutes FROM ROADMAP.STUDY_METRIC_HEARTRATE WHERE PRTCPT_DVC_ID = 1558;

SELECT DISTINCT TO_CHAR(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD') AS distinct_days
FROM ROADMAP.STUDY_METRIC_HEARTRATE WHERE PRTCPT_DVC_ID = 1558
ORDER BY distinct_days;

SELECT PRTCPT_DVC_ID, CAST(PRTCPT_DVC_ID AS NUMBER)
FROM ROADMAP.STUDY_METRIC_HEARTRATE
WHERE REGEXP_LIKE(PRTCPT_DVC_ID, '^[[:digit:]]+$');

SELECT TO_CHAR(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD') AS formatted_date
FROM ROADMAP.STUDY_METRIC_HEARTRATE
WHERE ROWNUM <= 10;

SELECT DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'STUDY_METRIC_HEARTRATE'
AND COLUMN_NAME = 'STUDY_METRIC_MSR_START_DT';

SELECT DISTINCT TO_CHAR(TO_DATE(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') AS distinct_days
FROM ROADMAP.STUDY_METRIC_HEARTRATE
WHERE PRTCPT_DVC_ID = 1558
ORDER BY distinct_days;


SELECT
  STUDY_METRIC_MSR_START_DT,
  STUDY_METRIC_MSR_END_DT,
  (
    (EXTRACT(day FROM duration) * 1440) +
    (EXTRACT(hour FROM duration) * 60) +
    EXTRACT(minute FROM duration)
  ) AS time_difference_in_minutes
FROM
  (
    SELECT
      STUDY_METRIC_MSR_START_DT,
      STUDY_METRIC_MSR_END_DT,
      NUMTODSINTERVAL(STUDY_METRIC_MSR_END_DT - STUDY_METRIC_MSR_START_DT, 'DAY') AS duration
    FROM
      ROADMAP.STUDY_METRIC_HEARTRATE
    WHERE
      PRTCPT_DVC_ID = 1558
  )
  
select * from roadmap.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 1558 and STUDY_METRIC_MSR_START_DT = '2020-09-28 15:28:50'
select * from roadmap.STUDY_METRIC_HEARTRATE where PRTCPT_DVC_ID = 1558 and STUDY_METRIC_MSR_END_DT = '2020-09-28 15:29:50'



SELECT
  STUDY_METRIC_MSR_START_DT,
  STUDY_METRIC_MSR_END_DT,
  (
    (EXTRACT(DAY FROM time_diff) * 24 * 60) + -- Convert days to minutes
    (EXTRACT(HOUR FROM time_diff) * 60) +     -- Convert hours to minutes
    EXTRACT(MINUTE FROM time_diff)            -- Add minutes
  ) AS time_difference_in_minutes
FROM
  (
    SELECT
      STUDY_METRIC_MSR_START_DT,
      STUDY_METRIC_MSR_END_DT,
      (TO_TIMESTAMP(STUDY_METRIC_MSR_END_DT, 'YYYY-MM-DD HH24:MI:SS') - 
       TO_TIMESTAMP(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS')) AS time_diff
    FROM
      roadmap.STUDY_METRIC_HEARTRATE
  );
  
  
  SELECT
  COUNT(CASE
    WHEN 
      (
        (EXTRACT(DAY FROM time_diff) * 1440) +  -- days to minutes
        (EXTRACT(HOUR FROM time_diff) * 60) +   -- hours to minutes
        EXTRACT(MINUTE FROM time_diff)          -- minutes
      ) != 1 THEN 1
    END) AS count_time_differences_not_equal_to_one
FROM
  (
    SELECT
      TO_TIMESTAMP(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS') AS start_timestamp,
      TO_TIMESTAMP(STUDY_METRIC_MSR_END_DT, 'YYYY-MM-DD HH24:MI:SS') AS end_timestamp,
      (TO_TIMESTAMP(STUDY_METRIC_MSR_END_DT, 'YYYY-MM-DD HH24:MI:SS') - 
       TO_TIMESTAMP(STUDY_METRIC_MSR_START_DT, 'YYYY-MM-DD HH24:MI:SS')) AS time_diff
    FROM
      roadmap.STUDY_METRIC_HEARTRATE

  );
  
  /*Checking the sleep variables data set for the entire table. Particularly if the sleep type 1, and 19 have same values on same dates for same participants.         */
  
  